name: hypercp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - _ipyw_jlab_nb_ext_conf=0.1
  - bottleneck=1.3
  - cdsapi=0.6
  - dask=2022.7
  - netcdf4=1.6
  - pip=23.0
  - py6s=1.9
  - pyqt=5.15
  - pyqtgraph=0.13
  - pyspectral=0.12
  - xarray=0.19
  - pip:
    - pysolar
    - fpdf2
    - tqdm
    - punpy
# prefix: /accounts/daurin/anaconda3
