name: hypercp
channels:
  - defaults
  - conda-forge
dependencies:
  - conda
  - python
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - anaconda
  - anaconda-navigator
  - navigator-updater
  - xarray
  - bottleneck
  - netcdf4
  - dask
  - pyqtgraph
  - pyspectral
  - pip
  - pip:
    - pysolar
    - fpdf2
    - tqdm
    - punpy
# prefix: /accounts/daurin/anaconda3
