name: Build

on:
  workflow_call:
    outputs:
      files:
        description: 'Artifact filenames.'
        value: |
          ${{ jobs.Build.outputs.ubuntu_artifact_filename }}
          ${{ jobs.Build.outputs.macos_artifact_filename }}
          ${{ jobs.Build.outputs.windows_artifact_filename }}

jobs:
  Build:
    name: Bundle

    runs-on: ${{ matrix.os }}
    defaults:  # Required for conda environment activation
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']

    steps:
      - name: Get Branch Name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: hypercp
          use-mamba: true

      - name: Cache Environment
        uses: actions/cache@v4
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER }}
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        id: cache

      - name: Update Environment
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mamba env update -n hypercp -f environment.yml
          mamba install --channel=conda-forge pyinstaller==6.6

      - name: Capture Environment
        run: |
          mamba info
          mamba list

      - name: Make Bundle
        run: |
          python make.py
          echo "BUNDLE_NAME=$(ls Bundled/dist | head -1 | xargs)" >> $GITHUB_ENV

      - name: Zip Bundle
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          directory: 'Bundled/dist/'
          path: '${{ env.BUNDLE_NAME }}'
          filename: '${{ env.BUNDLE_NAME }}.zip'

      - name: Upload Bundle
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUNDLE_NAME }}
          path: Bundled/dist/${{ env.BUNDLE_NAME }}.zip
          compression-level: 0
          # Double zip as need zip for release page (ideally want to prevent unzip from download artifact)
