on:
  push:
    branches:
      - workflow
#      - main
#      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
      - run: echo "${{ runner.name }} - ${{ runner.release }} - ${{ runner.cpu-model }}"
      - uses: actions/checkout@v4
        with:
          ref: 'workflow'  # branch to checkout
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: hypercp
      - run: pip install PyInstaller  # Not included in default environment
      - run: python make.py
      - uses: actions/upload-artifact@v3
        with:
          path: Bundled/dist/*
