on:
  push:
#    branches:
#      - main
#      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        activate-environment: hypercp
    - run: python make.py
    - uses: actions/upload-artifact@v3
      with:
        path: Bundled/dist/*
